// <auto-generated />
using System;
using Learnup.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Learnup.Infrastructure.Migrations
{
    [DbContext(typeof(LearnupDbContext))]
    [Migration("20260609152015_Update1")]
    partial class Update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Grammars.Grammar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EstimatedTime")
                        .HasColumnType("interval");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentGrammarId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentGrammarId");

                    b.ToTable("Grammar", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Grammars.GrammarLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GrammarId")
                        .HasColumnType("integer");

                    b.Property<int>("HtmlTag")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("VoiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrammarId");

                    b.ToTable("GrammarLesson", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Languages.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.LessonGrammar", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("GrammarId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "GrammarId");

                    b.HasIndex("GrammarId");

                    b.ToTable("LessonGrammar", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.LessonStory", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "StoryId");

                    b.HasIndex("StoryId");

                    b.ToTable("LessonStory", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.LessonVocab", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("VocabId")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "VocabId");

                    b.HasIndex("VocabId");

                    b.ToTable("LessonVocab", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Stories.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoverId")
                        .HasColumnType("integer");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Story", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Stories.StoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryItem", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Stories.StoryItemTimestamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("End")
                        .HasColumnType("real");

                    b.Property<float>("Start")
                        .HasColumnType("real");

                    b.Property<int>("StoryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("StoryItemId");

                    b.ToTable("StoryItemTimestamp", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserCourse", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstVisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserCourse", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserGrammar", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GrammarId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GrammarId");

                    b.HasIndex("GrammarId");

                    b.ToTable("UserGrammar", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserLesson", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LessonId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("LessonId1");

                    b.ToTable("UserLesson", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserStory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "StoryId");

                    b.HasIndex("StoryId");

                    b.ToTable("UserStory", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserVocab", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VocabId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "VocabId");

                    b.HasIndex("VocabId");

                    b.ToTable("UserVocab", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Vocabularies.Vocab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentVocabId")
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ParentVocabId");

                    b.ToTable("Vocab", (string)null);
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Courses.Course", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Languages.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Grammars.Grammar", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Grammars.Grammar", "ParentGrammar")
                        .WithMany("PrerequisiteGrammars")
                        .HasForeignKey("ParentGrammarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentGrammar");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Grammars.GrammarLesson", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Grammars.Grammar", "Grammar")
                        .WithMany("Lessons")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.Lesson", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Courses.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.LessonGrammar", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Grammars.Grammar", "Grammar")
                        .WithMany()
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Lessons.Lesson", "Lesson")
                        .WithMany("Grammars")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.LessonStory", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Lessons.Lesson", "Lesson")
                        .WithMany("Stories")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Stories.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.LessonVocab", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Lessons.Lesson", "Lesson")
                        .WithMany("Vocabs")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Vocabularies.Vocab", "Vocab")
                        .WithMany()
                        .HasForeignKey("VocabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Vocab");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Stories.StoryItem", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Stories.Story", "Story")
                        .WithMany("Items")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Stories.StoryItemTimestamp", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Stories.StoryItem", "StoryItem")
                        .WithMany("Timestamps")
                        .HasForeignKey("StoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoryItem");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserCourse", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Courses.Course", "Course")
                        .WithMany("Users")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserGrammar", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Grammars.Grammar", "Grammar")
                        .WithMany()
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Users.User", "User")
                        .WithMany("Grammars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserLesson", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Lessons.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Lessons.Lesson", null)
                        .WithMany("Users")
                        .HasForeignKey("LessonId1");

                    b.HasOne("Learnup.Domain.AggregateRoots.Users.User", "User")
                        .WithMany("Lessons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserStory", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Stories.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Users.User", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.UserVocab", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Users.User", "User")
                        .WithMany("Vocabs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Vocabularies.Vocab", "Vocab")
                        .WithMany()
                        .HasForeignKey("VocabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vocab");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Vocabularies.Vocab", b =>
                {
                    b.HasOne("Learnup.Domain.AggregateRoots.Languages.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnup.Domain.AggregateRoots.Vocabularies.Vocab", "ParentVocab")
                        .WithMany()
                        .HasForeignKey("ParentVocabId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Language");

                    b.Navigation("ParentVocab");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Courses.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Grammars.Grammar", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("PrerequisiteGrammars");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Lessons.Lesson", b =>
                {
                    b.Navigation("Grammars");

                    b.Navigation("Stories");

                    b.Navigation("Users");

                    b.Navigation("Vocabs");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Stories.Story", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Stories.StoryItem", b =>
                {
                    b.Navigation("Timestamps");
                });

            modelBuilder.Entity("Learnup.Domain.AggregateRoots.Users.User", b =>
                {
                    b.Navigation("Grammars");

                    b.Navigation("Lessons");

                    b.Navigation("Stories");

                    b.Navigation("Vocabs");
                });
#pragma warning restore 612, 618
        }
    }
}
